# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 21:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cnapWithService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRegistration', models.DateField(default=datetime.datetime(2017, 11, 23, 23, 49, 52, 889000))),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='historyOfRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.cnapWithService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='infoAboutCnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='servicesForCNAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(choices=[(b'Post', b'\xd0\x9f\xd0\xbe\xd0\xb4\xd0\xb0\xd1\x82\xd0\xb8 \xd0\xb4\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8'), (b'Get', b'\xd0\x9e\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8 \xd1\x80\xd0\xb5\xd0\xb7\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb0\xd1\x82'), (b'Registrer', b'\xd0\x97\xd0\xb0\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd1\x82\xd0\xb8\xd1\x81\xd1\x8c \xd0\xbd\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb9\xd0\xbe\xd0\xbc')], default=b'Post', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='cnapwithservice',
            name='nameOfZnap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.infoAboutCnap'),
        ),
        migrations.AddField(
            model_name='cnapwithservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.servicesForCNAP'),
        ),
    ]
