# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_auto_20171108_1540'),
        ('znapapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToZnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('service', models.CharField(max_length=226)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.UserProfile')),
                ('znap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='znapapi.Znap')),
            ],
        ),
    ]
