# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0002_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
