# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('znapapi', '0001_initial'),
        ('adminapi', '0005_admin_io'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='znap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='znapapi.Znap'),
            preserve_default=False,
        ),
    ]
