# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 13:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 40, 33, 141000))),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', '1')], max_length=1)),
                ('is_closed', models.BooleanField()),
                ('admin', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateapi.Rate'),
        ),
    ]
