# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 21, 42, 13, 496000)),
        ),
    ]
