# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0004_auto_20171110_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 4, 4, 29, 487000)),
        ),
    ]
