# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0005_auto_20171110_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='numOfTicket',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 1, 0, 57, 688000)),
        ),
    ]
