# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0044_auto_20171123_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 47, 53, 554000)),
        ),
    ]
