# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0045_auto_20171123_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 48, 43, 346000)),
        ),
    ]
