# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-01 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('znapapi', '0001_initial'),
        ('rateapi', '0048_auto_20171201_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='znap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='znapapi.Znap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 14, 0, 22, 410000)),
        ),
    ]
