# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapi', '0052_auto_20171217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 12, 30, 9, 248591)),
        ),
    ]
