# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2017, 11, 2, 21, 24, 32, 789000))),
            ],
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='quality',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='rate',
            name='is_closed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('1', '1')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='dialog',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.Admin'),
        ),
    ]
