# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20171102_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 21, 26, 3, 698000)),
        ),
    ]
