# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-08 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_auto_20171108_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 15, 29, 57, 953000)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.Admin'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
